### ISSUE TITLE
Open Link in New Tab -> Wrong tab order

### ISSUE THREAD

**Issue by ppoutine** [asamuzaK/sidebarTabs#114]
This is a bug I can reproduce:

1. Create a group of tabs
2. From one of those tabs (not the bottom one), start opening a few links by middle clicking the link
3. The first link works correctly; the new tab is one spot below the current tab
4. Subsequently opened links are out of order; in SidebarTabs, they are at the bottom of the current tab group. In the Firefox horizontal tab bar, however, they still appear one spot after the current tab. The two tab displays are now out of sync.

In SidebarTabs options, "Always put the newly opened tab at the end of the group" is unchecked.

Thanks! lmk if you need any other info or logs or something

**Comment by asamuzaK** [comment]
confirmed

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by ppoutine** [comment]
> 
> 
> [Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

It's fixed in this build, thank you so much! <3

**Comment by asamuzaK** [comment]
Found out that there is still an issue when `browser.tabs.insertAfterCurrent` and `browser.tabs.insertRelatedAfterCurrent` are both set to `false`.

Reopened

**Comment by asamuzaK** [comment]
[2nd try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
